language: java
jdk:
    - oraclejdk11
before_script:
    - cd finish
script:
    - mvn clean verify 
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: osJ1BpDrO19/9es/FCOQ4doXMbQ2ntuhbVheJWsgJf8+1HC7zYPTJkPiwKW3Jxt5QCXBHjk6HhbO+Vp8kr8J4DLJOzE2sGstWny8BzB2asvVLcJDqT9osKbNI7gF6jY61s8DPM3n7AIl8JYtLfwkfidhAxmtgN04zNKQMxr1h0mGBDk1NKV0gZHv3TAQqCJLS56YdnjIu8Ig52Ud0VA2F1hgrOpwPEhwYAMG++IkZr3Scm5QGYvoloQjXzBKKaQA4eb6KkvvA/79qCaH+3A0mE+hZAN5IADzF21O6eC9li5Xy9+iOL84YW2Sb+co/WvYLPzKu7lWGpiQ311UtKvX2u7/tKtlpSTOeK7QhdDT2AzgcoeVJKf2w7Q7x0GJmypVrzCDIon9bBw4YAXwbj1jkJUCm9xDXIXJ7cQl2JtfdM4K4NNT6GZoLNr94cJHcI1VeFdg/e8GTfcqjSAAcjo7fmkSKp5q+Y4V0JFdtdQvxZ5Rm/4gZRW6qMzNzXGWbkogw6CAh8uVyhRDiGNTGLKm0RwFNyYoWL6GsyMBrbpDP0NqWCOhXNLEyHGdvahuJOMNuaa9Al+BltxTgY6M+KXg31mdZL5fhCx9Z3gna32X7uuSRvWT5SvMzgTqPG+cSPrzoEyLpGMfrDOjjhLHFbOcqIU1uxZF55nXMgNVaO3HbFk=
    on_success: never
    on_failure: always
branches:
  only:
  - master
  - dev
  - qa
